# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe407f03091e4352024a56125c0bb8b26f047577ee4cff4e1022047702d98e6c73404af6eb7f51c1329f5a640e7698eda793ea43b88ce98e23d6d60cf366263

test:
  secret_key_base: 9e83fa5997891f94f8a2cb5577180be505cae985eedd76637b3707e4473c67c1d1ca92e6c4eb94794adebc71078c29e766ec184a5d6cfdc23a47ce9b10fbedc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
